server:
  port: 8091



spring:
  application:
    name: tache-service
  datasource:
    url: jdbc:mysql://localhost:3306/task?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/